language: cpp
sudo: required
dist: trusty
install:
    # /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    # /usr/bin/clang is 3.4, lets override with modern one.
    - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - sudo apt-get install -y qt5-default qttools5-dev-tools p7zip-full
addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - g++-4.9
        - clang
before_script:
    - curl -fsSL "http://download.qt.io/official_releases/qtcreator/4.2/4.2.0/installer_source/linux_gcc_64_rhel66/qtcreator_dev.7z" -o qt-dev.7z
    - 7z x -y qt-dev.7z -o"qt-src"
    - curl -fsSL "http://download.qt.io/official_releases/qtcreator/4.2/4.2.0/installer_source/linux_gcc_64_rhel66/qtcreator.7z" -o qt-bin.7z
    - 7z x -y qt-bin.7z -o"qt-bin"
script:
    - qmake qtc-sourcetrail.pro -r "QTC_SOURCE=qt-src" "QTC_BUILD=qt-bin\bin" "LIBS+=-Lqt-libs" "OUTPUT_PATH=artifacts\4.2.1"
    - make
after_script:
  - tar -cf $TRAVIS_BUILD_DIR/qtc-sourcetrail-linux.tar.gz $TRAVIS_BUILD_DIR/qt-bin/bin/lib/qtcreator/plugins/*
deploy:
  provider: releases
  api_key:
    secure: "RMvCoCzTj44tBCRmuVh9IXXh3IX8hWjzurmfpVB/fZU1NZEn9XBTyV5ngD9ZGw2NCRnN7t4KjHaJZCRWBroIUq0G5aH/nYz6/jnlIL4SRCiTsnl8bYHdLzJOtdXnavCIbgAVgDFoNfCsHF14XfRQakrMxSOp+4LKSYNWIdV3rBMPdL4m2OhVOtuJVzge+1IrveEuHsoAcaAlnV7GiSwpWd0CX/v8wcIQ+s6QYA1HEKOfuElVtLkKrZXWq11hO3zHLHFyXzMnwUoPQjZPkR6yOA/aZoxy4ovlooN/2Aa8EgAFnEckXFqGq4Rta6EHsg/hezNSZDzFMXE7UL9/vnqPlyVBX6cU1w29ro7EWnK+62gr9FQqbCkViIxnrJau4bB4qHK+3pvIwrubCnFXkSs9kt4lcZdR+midz35v3pV+D0ZmcEO1cQN8EDQqohpsvGZ/XiF33br/2/g4R2XlB3bDD17aRipGjsOWCoxevh4XDe5ivymhxilseIO1Af1SHbk8z4vhc6ywyppvvQgWGTYInbMEXf8m9zTvVWDZqFHmET0GABSmY0QbuLmaQZrtK6qjisXva06O2P9+Wj69d4i1JxLwxHNbJv60DLu7xGmGanom9+yJaPfJIk/Rx+trewvk9Z0LR3fOcyxnDyDFdKfbIRxDiKspLB+jZ6A97/W+9i0="
  file: $TRAVIS_BUILD_DIR/qtc-sourcetrail-linux.tar.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true
